development:
  adapter: postgresql
  encoding: unicode
  database: earmark_development
  pool: 5
  username: efatsi
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: earmark_test
  pool: 5
  username: efatsi
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: earmark_production
  pool: 5
  username: efatsi
  password:
  host: localhost
